-- AlterTable
ALTER TABLE "rental_items" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "rentals" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "vendors" DROP COLUMN IF EXISTS "phone";
ALTER TABLE "vendors" DROP COLUMN IF EXISTS "status";
ALTER TABLE "vendors" DROP COLUMN IF EXISTS "totalSalesToday";
